### ISSUE TITLE
Updating leapseconds file should be possible without updating cookbook

### ISSUE THREAD

**Issue by jrosenboom** [chef-cookbooks/ntp#152]
Currently, updates leapsecond files are only published for new cookbooks, but if I deploy a server now with e.g. cookbook version 2.0.0, I don't want to have to upgrade to some possibly incompatible version 3.0.0 in 2017 just to avoid using outdated data.

So IMHO the correct solution would be to install a stable URL somewhere, where this file will get updated, and do a remote_file from there instead of using cookbook_file resource.

**Comment by tas50** [comment]
The remote_file method is something we've gone back and forth on for a while. Since the leap file isn't versioned it's a bit trickier and requires us to hit their server a lot to ensure the file is up to date.  In the past when we do things like this organizations rightfully blocked the chef-client from hitting them as we drive up hosting bills. I'd like to avoid hurting other communities by shipping big bills their way. I'd be open to using the included file by default and allowing for a URL of your choosing to override that.  That URL should be nil by default though so people can just self host the files.

**Comment by tas50** [comment]
I'm going to close this out at the moment since there are technical problems that keep us from doing this any other way.
